// This file will be auto-generated by Supabase CLI
// For now, use this placeholder and replace with actual types later
// Run: npx supabase gen types typescript --project-id your-project-id > types/database.ts

export type Database = {
  public: {
    Tables: {
      // Define your tables here as you create them
      // Example:
      // users: {
      //   Row: { id: string; email: string; created_at: string }
      //   Insert: { id?: string; email: string; created_at?: string }
      //   Update: { id?: string; email?: string; created_at?: string }
      // }
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
